version: "3.8"

services:
  blue1:
    image: ${DOCKERHUB_USERNAME}/lol-team-balance-tool-back:latest
    container_name: lol-back-blue1
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: always

  blue2:
    image: ${DOCKERHUB_USERNAME}/lol-team-balance-tool-back:latest
    container_name: lol-back-blue2
    ports:
      - "8082:8080"
    networks:
      - app-network
    restart: always

  green1:
    image: ${DOCKERHUB_USERNAME}/lol-team-balance-tool-back:latest
    container_name: lol-back-green1
    ports:
      - "8083:8080"
    networks:
      - app-network
    restart: always

  green2:
    image: ${DOCKERHUB_USERNAME}/lol-team-balance-tool-back:latest
    container_name: lol-back-green2
    ports:
      - "8084:8080"
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: lol-back-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/service-url.inc:/etc/nginx/conf.d/service-url.inc
    networks:
      - app-network
    depends_on:
      - blue1
      - blue2
      - green1
      - green2
    restart: always

networks:
  app-network:
    driver: bridge
